# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20161118_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='groupitem', to='items.ItemOfGroup'),
        ),
        migrations.AlterField(
            model_name='group',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
