# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20161118_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemofgroup',
            old_name='groupname',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='limit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
