# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20161123_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='importance',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
